"""add_provision_url_to_customer_webhooks

Revision ID: 64e345a375f1
Revises: 3cc3ae5bc5c3
Create Date: 2026-09-03 01:37:12.821927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e345a375f1'
down_revision: Union[str, Sequence[str], None] = '3cc3ae5bc5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_webhooks', sa.Column('provision_url', sa.String(length=500), nullable=True))
    op.alter_column('customer_webhooks', 'secret_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_webhooks', 'secret_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('customer_webhooks', 'provision_url')
    # ### end Alembic commands ###
