"""create_products_and_memberships_tables

Revision ID: 6dbc677f5802
Revises: 64e345a375f1
Create Date: 2026-09-03 18:31:35.547893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbc677f5802'
down_revision: Union[str, Sequence[str], None] = '64e345a375f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('service_url', sa.String(length=255), nullable=True),
    sa.Column('provision_endpoint', sa.String(length=100), nullable=True),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('api_secret_previous', sa.Text(), nullable=True),
    sa.Column('last_key_rotation_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('membership_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price_mxn', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('features_payload', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_plans_id'), 'membership_plans', ['id'], unique=False)
    op.create_index(op.f('ix_membership_plans_product_id'), 'membership_plans', ['product_id'], unique=False)
    op.create_index(op.f('ix_membership_plans_slug'), 'membership_plans', ['slug'], unique=False)
    op.create_table('customer_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('mp_preapproval_id', sa.String(length=100), nullable=True),
    sa.Column('external_tenant_id', sa.String(length=100), nullable=True),
    sa.Column('custom_features_override', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_subscriptions_customer_id'), 'customer_subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_subscriptions_external_tenant_id'), 'customer_subscriptions', ['external_tenant_id'], unique=False)
    op.create_index(op.f('ix_customer_subscriptions_id'), 'customer_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_subscriptions_mp_preapproval_id'), 'customer_subscriptions', ['mp_preapproval_id'], unique=False)
    op.create_index(op.f('ix_customer_subscriptions_plan_id'), 'customer_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_customer_subscriptions_status'), 'customer_subscriptions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_subscriptions_status'), table_name='customer_subscriptions')
    op.drop_index(op.f('ix_customer_subscriptions_plan_id'), table_name='customer_subscriptions')
    op.drop_index(op.f('ix_customer_subscriptions_mp_preapproval_id'), table_name='customer_subscriptions')
    op.drop_index(op.f('ix_customer_subscriptions_id'), table_name='customer_subscriptions')
    op.drop_index(op.f('ix_customer_subscriptions_external_tenant_id'), table_name='customer_subscriptions')
    op.drop_index(op.f('ix_customer_subscriptions_customer_id'), table_name='customer_subscriptions')
    op.drop_table('customer_subscriptions')
    op.drop_index(op.f('ix_membership_plans_slug'), table_name='membership_plans')
    op.drop_index(op.f('ix_membership_plans_product_id'), table_name='membership_plans')
    op.drop_index(op.f('ix_membership_plans_id'), table_name='membership_plans')
    op.drop_table('membership_plans')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
