"""add_landing_path_to_products

Revision ID: 8b959bb2b705
Revises: 6dbc677f5802
Create Date: 2026-09-03 20:43:55.473342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b959bb2b705'
down_revision: Union[str, Sequence[str], None] = '6dbc677f5802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('landing_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'landing_path')
    # ### end Alembic commands ###
